name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  tag_repo:
    runs-on: ubuntu-18.04
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v1
      - name: Update mn2pdf.jar
        run: |
          rm -f bin/mn2pdf.jar
          rake bin/mn2pdf.jar
      - name: Update gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run specs
        run: |
          bundle exec rake
      - name: Publish to rubygems.org
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}