name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: 'skip'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - if: github.event_name == 'workflow_dispatch' && inputs.next_version != 'skip'
        run: |
          rm -f bin/mn2pdf.jar

      - run: bundle exec rake bin/mn2pdf.jar

      - run: bundle exec rake

      - run: gem install gem-release

      - run: |
          git config user.name "metanorma-ci"
          git config user.email "metanorma-ci@users.noreply.github.com"

      - if: github.event_name == 'workflow_dispatch' && inputs.next_version != 'skip'
        run: |
          gem bump --version ${{ inputs.next_version }} --no-commit
          git add -u lib/mn2pdf/version.rb
          git commit -m "Bump version to ${mnconvert_VERSION}"
          git tag v${{ inputs.next_version }}
          git push origin HEAD:${GITHUB_REF} --tags

      - name: Publish to rubygems.org
        env:
          RUBYGEMS_API_KEY: ${{secrets.METANORMA_CI_RUBYGEMS_API_KEY}}
        run: |
          gem install gem-release
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF
          chmod 0600 ~/.gem/credentials
          gem release

      - if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
        with:
          assignees: CAMOBAP
          update_existing: true
          search_existing: all

